### ISSUE TITLE
Authorize.net - The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by SilverSearcher** [smartstoreag/SmartStoreNET#1260]
Hi -

Having an issue with the Authorize plug-in on confirm order - "The request was aborted: Could not create SSL/TLS secure channel." - I just updated and recompiled the latest 3.0.3 for the Plugins branch.

I have an SSL cert, the site is set to SSL and my default is TLS1.2 (not sure about the plug-in). I'm in sandbox/authorize mode. ID/Key is correct for Authorize.

I'd appreciate any insights or knowledge you have. Thanks

**Comment by Michael-Herzog** [comment]
Hi, thanks for reporting. This issue should be resolved now. Please pull the current code and try again.

**Comment by SilverSearcher** [comment]
Hmmm weird... I see you added TLS1.2 and I'd have figured this would have worked, but still getting the same issue.

**Comment by Michael-Herzog** [comment]
Are you testing directly in VS or a deployed online shop? I've often experienced a ddl caching issue in the later.

**Comment by SilverSearcher** [comment]
Deployed online... it's SSL ready (intended production)

- Took down new code.
- Removed "plugin" from solution, added new code to solution.
- Clicked to Build
- Copied over changes.
- Cleared all cache and restarted application

How would I deal with the .dll caching?

**Comment by Michael-Herzog** [comment]
The first thing I do in these cases is to alter optimizeCompilations="true" in the web.config to false. 
(which will restart the shop) then restore it to the original. The theory is that this will clear the cache automatically and this approach worked for me in 85% of all cases. 
 
But there were some cases in which I had to remove the dll directly for the .NET cache by tracking it down with a search in the corresponding Windows directory.

**Comment by SilverSearcher** [comment]
k - got it and works... found this on the dll cache remove... I guess it was a caching issue -

https://stackoverflow.com/questions/5721415/website-is-running-a-cached-dll-somehow-after-changing-it

I nuked the C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\ - contents
and the: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\

That fixed it... weird on the DLL cache.

Thanks so much for your help and the quick fix on this. Very much appreciate - it was driving me insane.
