### ISSUE TITLE
Error while Importing Categories

### ISSUE THREAD

**Issue by FarrukhRB** [smartstoreag/SmartStoreNET#1406]
Hi,
I'm facing an error while importing data of categories from excel sheet. 
Import task is not executing. 
Please see the attached Image for error as no information about error is provided. 
Also excel sheet is attached from which I'm trying to import data. 

![error](https://user-images.githubusercontent.com/5442605/38360067-eae69ca0-38e2-11e8-89f2-396c2051dab7.png)
[Categories.xlsx](https://github.com/smartstoreag/SmartStoreNET/files/1879492/Categories.xlsx)

**Comment by mgesing** [comment]
Can one of the following [solutions](http://community.smartstore.com/index.php?/topic/49147-how-to-empty-guest-carts/#entry274787) solve the problem?

**Comment by Michael-Herzog** [comment]
Hi,

there was a little typo which we have already corrected in the current developer branch. 
Please write the URL like this:
http://www.pcpearl.com/tas**k**scheduler

**Comment by FarrukhRB** [comment]
Hi, 
Thanks for your prompt reply. fixing the URL has removed the warning but still the Send Email Task is still Showing Waiting and Queued Emails are not sent. (Please see Attached Screen Shots)
![error log](https://user-images.githubusercontent.com/5442605/38874659-0d1fb49e-4272-11e8-86c2-086b2211586a.png)
![scheduled tasks](https://user-images.githubusercontent.com/5442605/38874662-0d57724e-4272-11e8-813d-2f9a4438a944.png)
![error log 2](https://user-images.githubusercontent.com/5442605/38874777-5b943dd4-4272-11e8-9442-843c6ebcb72b.png)

**Comment by FarrukhRB** [comment]
Hi, 

Thanks for Your response. 
Issue is resolved. 

Just needed to add both URLs "With and Without www." in Host Section of Store. 

Thanks again for you Help.
